### ISSUE TITLE
수집할 데이터 확실히 정하기

### ISSUE THREAD

**Issue by lmwljw98** [team-asdf/yaboja-crawler#9]
타이틀, 컨텐츠, 이미지 등 정확히 어떤걸 수집할 것인지 확실히 정하기

**Comment by ghyeon0** [comment]
title: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    content: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    url: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    cnt: {
      type: DataTypes.INTEGER(11),
      allowNull: true,
      defaultValue: '0'
    },
	source: {
	  type: DataTypes.TEXT,
	  allowNull: true
	},
	keyword: {
	  type: DataTypes.TEXT,
	  allowNull: true
	},
    createdAt: {
      type: DataTypes.DATE,
      allowNull: true
    }
+ image?

**Comment by gwons** [comment]
아아 Image 어쩌죠

**Comment by ghyeon0** [comment]
디비에 넣어주세요.. 이미지 있으면 이미지 링크 넣고 아니면 ogimage라도 넣겠습니다..

**Comment by gwons** [comment]
[{
idx: 1,
title: "테스트 제목입니다. (1)",
content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
url: "blog.naver.com",
cnt: 0,
source: "naver",
keyword: "python,django",
image: "https://dummyimage.com/600x400/000/fff",
createdAt: "2018-10-03"
}]

추가했습니다
